<?php

use Illuminate\Database\Seeder;

class FUserNamesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
       //   DB::table('user_names')->truncate();

        \App\Models\UserNames::insert([

            ['name' => 'Евстахий', 'en_name'=>'Evstahiy'],
            ['name' => 'Егор', 'en_name'=>'Egor'],
            ['name' => 'Елисей', 'en_name'=>'Elisay'],
            ['name' => 'Емельян', 'en_name'=>'Emelian'],
            ['name' => 'Еремей', 'en_name'=>'Eremey'],
            ['name' => 'Ефим', 'en_name'=>'Efim'],
            ['name' => 'Ефрем', 'en_name'=>'Efrim'],
            ['name' => 'Ждан', 'en_name'=>'Gdan'],
            ['name' => 'Жерар', 'en_name'=>'Dgerar'],
            ['name' => 'Жигер', 'en_name'=>'Dgiger'],
            ['name' => 'Закир', 'en_name'=>'Zakir'],
            ['name' => 'Заур', 'en_name'=>'Zayr'],
            ['name' => 'Захар', 'en_name'=>'Zahar'],
            ['name' => 'Зенон', 'en_name'=>'Zenon'],
            ['name' => 'Зигмунд', 'en_name'=>'Zygmund'],
            ['name' => 'Зиновий', 'en_name'=>'Zinoviy'],
            ['name' => 'Зураб', 'en_name'=>'Zurab'],
            ['name' => 'Зуфар', 'en_name'=>'Zyfar'],
            ['name' => 'Ибрагим', 'en_name'=>'Ibragim'],
            ['name' => 'Иван', 'en_name'=>'Ivan'],
            ['name' => 'Игнат', 'en_name'=>'Ignat'],
            ['name' => 'Игнатий', 'en_name'=>'Ignatiy'],
            ['name' => 'Игорь', 'en_name'=>'Igor'],
            ['name' => 'Иисус', 'en_name'=>'Jesus'],
            ['name' => 'Ильгиз', 'en_name'=>'Ilgiz'],
            ['name' => 'Ильнур', 'en_name'=>'Ilnur'],
            ['name' => 'Ильшат', 'en_name'=>'Ilshat'],
            ['name' => 'Илья', 'en_name'=>'Illya'],
            ['name' => 'Имран', 'en_name'=>'Imran'],
            ['name' => 'Иннокентий', 'en_name'=>'Innokantiy'],
            ['name' => 'Ираклий', 'en_name'=>'Irakly'],
            ['name' => 'Исаак', 'en_name'=>'Issaac'],
            ['name' => 'Исаакий', 'en_name'=>'Issaakiy'],
            ['name' => 'Исидор', 'en_name'=>'Isidor'],
            ['name' => 'Искандер', 'en_name'=>'Iskander'],
            ['name' => 'Ислам', 'en_name'=>'Islam'],
            ['name' => 'Исмаил', 'en_name'=>'Ismail'],
            ['name' => 'Итан', 'en_name'=>'Itan'],
            ['name' => 'Казбек', 'en_name'=>'Kazbek'],
            ['name' => 'Камиль', 'en_name'=>'Kamil'],
            ['name' => 'Карен', 'en_name'=>'Karen'],
            ['name' => 'Карим', 'en_name'=>'Karym'],
            ['name' => 'Карл', 'en_name'=>'Karl'],
            ['name' => 'Ким', 'en_name'=>'Kym'],
            ['name' => 'Кир', 'en_name'=>'Kyr'],
            ['name' => 'Кирилл', 'en_name'=>'Kyrill'],
            ['name' => 'Клаус', 'en_name'=>'Klaus'],
            ['name' => 'Клим', 'en_name'=>'Klim'],
            ['name' => 'Конрад', 'en_name'=>'Konrad'],
            ['name' => 'Константин', 'en_name'=>'Konstantin'],
            ['name' => 'Корнелий', 'en_name'=>'Korneliy'],
            ['name' => 'Кристиан', 'en_name'=>'Cristian'],
            ['name' => 'Кузьма', 'en_name'=>'Kuzma'],
            ['name' => 'Лаврентий', 'en_name'=>'Lavrentiy'],
            ['name' => 'Лев', 'en_name'=>'Lev'],
            ['name' => 'Леон', 'en_name'=>'Leon'],
            ['name' => 'Леонард', 'en_name'=>'Leonard'],
            ['name' => 'Леонид', 'en_name'=>'Leonyd'],
            ['name' => 'Леопольд', 'en_name'=>'Leopold'],
            ['name' => 'Лоренс', 'en_name'=>'Lourens'],
            ['name' => 'Лука', 'en_name'=>'Luka'],
            ['name' => 'Лукиллиан', 'en_name'=>'Lukillian'],
            ['name' => 'Лукьян', 'en_name'=>'Lukyan'],
            ['name' => 'Любомир', 'en_name'=>'Lubomyr'],
            ['name' => 'Людвиг', 'en_name'=>'Ludvig'],
            ['name' => 'Людовик', 'en_name'=>'Ludo'],
            ['name' => 'Люций', 'en_name'=>'Luciy'],
            ['name' => 'Маджид', 'en_name'=>'Madjid'],
            ['name' => 'Майкл', 'en_name'=>'Mikle'],
            ['name' => 'Макар', 'en_name'=>'Makar'],
            ['name' => 'Макарий', 'en_name'=>'Makariy'],
            ['name' => 'Максим', 'en_name'=>'Maxim'],
            ['name' => 'Максимилиан', 'en_name'=>'Maximilian'],
            ['name' => 'Максуд', 'en_name'=>'Maksud'],
            ['name' => 'Мансур', 'en_name'=>'Mansur'],
            ['name' => 'Мар', 'en_name'=>'Mar'],
            ['name' => 'Марат', 'en_name'=>'Marat'],
            ['name' => 'Марк', 'en_name'=>'Mark'],
            ['name' => 'Марсель', 'en_name'=>'Marsell'],
            ['name' => 'Матвей', 'en_name'=>'Matvei'],
            ['name' => 'Махмуд', 'en_name'=>'Mahmud'],
            ['name' => 'Мика', 'en_name'=>'Mika'],
            ['name' => 'Микула', 'en_name'=>'Mykula'],
            ['name' => 'Мирон', 'en_name'=>'Miron'],
            ['name' => 'Мирослав', 'en_name'=>'Miroslav'],
            ['name' => 'Михаил', 'en_name'=>'Mihail'],
            ['name' => 'Мстислав', 'en_name'=>'Mstyslav'],
            ['name' => 'Мурат', 'en_name'=>'Murat'],
            ['name' => 'Муслим', 'en_name'=>'Muslim'],
            ['name' => 'Мухаммед', 'en_name'=>'Muhamed'],
            ['name' => 'Мэтью', 'en_name'=>'Matiy'],
            ['name' => 'Назар', 'en_name'=>'Nazar'],
            ['name' => 'Наиль', 'en_name'=>'Nail'],
            ['name' => 'Никита', 'en_name'=>'Nikita'],
            ['name' => 'Никодим', 'en_name'=>'Nikodym'],
            ['name' => 'Никола', 'en_name'=>'Nikola'],
            ['name' => 'Николай', 'en_name'=>'Nikolay'],
            ['name' => 'Нильс', 'en_name'=>'Nils'],
            ['name' => 'Огюст', 'en_name'=>'Ogust'],
            ['name' => 'Олег', 'en_name'=>'Oleg'],
            ['name' => 'Оливер', 'en_name'=>'Oliver'],
            ['name' => 'Орест', 'en_name'=>'Orest'],
            ['name' => 'Орландо', 'en_name'=>'Orlando'],
            ['name' => 'Оскар', 'en_name'=>'Oskar'],
            ['name' => 'Остап', 'en_name'=>'Ostap'],
            ['name' => 'Остин', 'en_name'=>'Ostin'],
            ['name' => 'Пётр', 'en_name'=>'Petr'],
            ['name' => 'Павел', 'en_name'=>'Pavel'],
            ['name' => 'Патрик', 'en_name'=>'Patric'],
            ['name' => 'Педро', 'en_name'=>'Pedro'],
            ['name' => 'Перри', 'en_name'=>'Perry'],
            ['name' => 'Платон', 'en_name'=>'Platon'],
            ['name' => 'Потап', 'en_name'=>'Potap'],
            ['name' => 'Прохор', 'en_name'=>'Prohor'],
            ['name' => 'Савва', 'en_name'=>'Savva'],
            ['name' => 'Савелий', 'en_name'=>'Saveliy'],
            ['name' => 'Саид', 'en_name'=>'Said'],
            ['name' => 'Самат', 'en_name'=>'Samat'],
            ['name' => 'Самвел', 'en_name'=>'Samvell'],
            ['name' => 'Самир', 'en_name'=>'Samir'],
            ['name' => 'Самуил', 'en_name'=>'Samuil'],
            ['name' => 'Сани', 'en_name'=>'Sany'],
            ['name' => 'Святослав', 'en_name'=>'Svatoslav'],
            ['name' => 'Севастьян', 'en_name'=>'Sevastian'],
            ['name' => 'Семён', 'en_name'=>'Semen'],
            ['name' => 'Серафим', 'en_name'=>'Seraphim'],
            ['name' => 'Сергей', 'en_name'=>'Serghiy'],
            ['name' => 'Сидор', 'en_name'=>'Sydor'],
            ['name' => 'Спартак', 'en_name'=>'Spartak'],
            ['name' => 'Станислав', 'en_name'=>'Stanislav'],
            ['name' => 'Степан', 'en_name'=>'Stetpan'],
            ['name' => 'Султан', 'en_name'=>'Sultan'],
            ['name' => 'Тагир', 'en_name'=>'Tagyr'],
            ['name' => 'Тайлер', 'en_name'=>'Tayler'],
            ['name' => 'Тамаз', 'en_name'=>'Tamaz'],
            ['name' => 'Тамерлан', 'en_name'=>'Tamerlan'],
            ['name' => 'Тарас', 'en_name'=>'Taras'],
            ['name' => 'Тигран', 'en_name'=>'Tigran'],
            ['name' => 'Тимофей', 'en_name'=>'Tymofey'],
            ['name' => 'Тимур', 'en_name'=>'Timur'],
            ['name' => 'Тихон', 'en_name'=>'Tihon'],
            ['name' => 'Томас', 'en_name'=>'Tomas'],
            ['name' => 'Трофим', 'en_name'=>'Trophim'],
            ['name' => 'Уинслоу', 'en_name'=>'Uinslow'],
            ['name' => 'Умар', 'en_name'=>'Umar'],
            ['name' => 'Устин', 'en_name'=>'Ustin'],
            ['name' => 'Фёдор', 'en_name'=>'Fedor'],
            ['name' => 'Фазиль', 'en_name'=>'Phasil'],
            ['name' => 'Фарид', 'en_name'=>'Faryd'],
            ['name' => 'Федот', 'en_name'=>'Fedot'],
            ['name' => 'Феликс', 'en_name'=>'Felics'],
            ['name' => 'Филипп', 'en_name'=>'Filip'],
            ['name' => 'Флор', 'en_name'=>'Flor'],
            ['name' => 'Фома', 'en_name'=>'Foma'],
            ['name' => 'Фред', 'en_name'=>'Fred'],
            ['name' => 'Фридрих', 'en_name'=>'Fridryh'],
            ['name' => 'Хабиб', 'en_name'=>'Habib'],
            ['name' => 'Хаким', 'en_name'=>'Hakim'],
            ['name' => 'Харитон', 'en_name'=>'hariton'],
            ['name' => 'Цезарь', 'en_name'=>'Cesar'],
            ['name' => 'Цефас', 'en_name'=>'Cefas'],
            ['name' => 'Цицерон', 'en_name'=>'Cyceron'],
            ['name' => 'Чарльз', 'en_name'=>'Charls'],
            ['name' => 'Чеслав', 'en_name'=>'Cheslav'],
            ['name' => 'Чингиз', 'en_name'=>'Chingiz'],
            ['name' => 'Шамиль', 'en_name'=>'Shamil'],
            ['name' => 'Шарль', 'en_name'=>'Sharl'],
            ['name' => 'Шерлок', 'en_name'=>'Sherlok'],
            ['name' => 'Эдгар', 'en_name'=>'Edgar'],
            ['name' => 'Эдуард', 'en_name'=>'Eduard'],
            ['name' => 'Эльдар', 'en_name'=>'Eldar'],
            ['name' => 'Эмиль', 'en_name'=>'Emil'],
            ['name' => 'Эмин', 'en_name'=>'Emin'],
            ['name' => 'Эрик', 'en_name'=>'Eric'],
            ['name' => 'Эркюль', 'en_name'=>'Ercyul'],
            ['name' => 'Эрмин', 'en_name'=>'Ermyn'],
            ['name' => 'Эузебио', 'en_name'=>'Euz '],
            ['name' => 'Юлиан', 'en_name'=>'Julian'],
            ['name' => 'Юлий', 'en_name'=>'Juliy'],
            ['name' => 'Юнус', 'en_name'=>'Yunus'],
            ['name' => 'Юрий', 'en_name'=>'Yuriy'],
            ['name' => 'Юстиниан', 'en_name'=>'Ustinian'],
            ['name' => 'Юстус', 'en_name'=>'Yustus'],
            ['name' => 'Яков', 'en_name'=>'Yakov'],
            ['name' => 'Ян', 'en_name'=>'Yan'],
            ['name' => 'Яромир', 'en_name'=>'Yaromyr'],
            ['name' => 'Ярослав', 'en_name'=>'Yaroslav'],
            
            
        ]);
    }
}
