<?php

use Illuminate\Database\Seeder;

class SUserNamesSeeder extends Seeder {

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
       // DB::table('user_names')->truncate();

        \App\Models\UserNames::insert([

            ['name' => 'Августа', 'en_name'=>'Augusta',
                'gender' => '1'],
            ['name' => 'Августина', 'en_name'=>'Augustina',
                'gender' => '1'],
            ['name' => 'Авдотья', 'en_name'=>'Avdotya',
                'gender' => '1'],
            ['name' => 'Аврора', 'en_name'=>'Avrora',
                'gender' => '1'],
            ['name' => 'Агапия', 'en_name'=>'Agapia',
                'gender' => '1'],
            ['name' => 'Агата', 'en_name'=>'Agata',
                'gender' => '1'],
            ['name' => 'Агафья', 'en_name'=>'Agaphia',
                'gender' => '1'],
            ['name' => 'Аглая', 'en_name'=>'Aglaya',
                'gender' => '1'],
            ['name' => 'Агния', 'en_name'=>'Agniya',
                'gender' => '1'],
            ['name' => 'Агунда', 'en_name'=>'Agunda',
                'gender' => '1'],
            ['name' => 'Ада', 'en_name'=>'Ada',
                'gender' => '1'],
            ['name' => 'Аделаида', 'en_name'=>'Adelaida',
                'gender' => '1'],
            ['name' => 'Аделина', 'en_name'=>'Adelina',
                'gender' => '1'],
            ['name' => 'Адель', 'en_name'=>'Adel',
                'gender' => '1'],
            ['name' => 'Адиля', 'en_name'=>'Adyl',
                'gender' => '1'],
            ['name' => 'Адриана', 'en_name'=>'Adriana',
                'gender' => '1'],
            ['name' => 'Аза', 'en_name'=>'Aza',
                'gender' => '1'],
            ['name' => 'Азалия', 'en_name'=>'Azalia',
                'gender' => '1'],
            ['name' => 'Азиза', 'en_name'=>'Aziza',
                'gender' => '1'],
            ['name' => 'Аида', 'en_name'=>'Aida',
                'gender' => '1'],
            ['name' => 'Аиша', 'en_name'=>'Aisha',
                'gender' => '1'],
            ['name' => 'Айгерим', 'en_name'=>'Aigerim',
                'gender' => '1'],
            ['name' => 'Айгуль', 'en_name'=>'Aigul',
                'gender' => '1'],
            ['name' => 'Айлин', 'en_name'=>'Ailyn',
                'gender' => '1'],
            ['name' => 'Айнагуль', 'en_name'=>'Ainagul',
                'gender' => '1'],
            ['name' => 'Айнур', 'en_name'=>'Ainur',
                'gender' => '1'],
            ['name' => 'Айсель', 'en_name'=>'Aisel',
                'gender' => '1'],
            ['name' => 'Айсун', 'en_name'=>'Aisun',
                'gender' => '1'],
            ['name' => 'Айсылу', 'en_name'=>'Aisily',
                'gender' => '1'],
            ['name' => 'Аксинья', 'en_name'=>'Acsinya',
                'gender' => '1'],
            ['name' => 'Алёна', 'en_name'=>'Alena',
                'gender' => '1'],
            ['name' => 'Алана', 'en_name'=>'Alana',
                'gender' => '1'],
            ['name' => 'Алевтина', 'en_name'=>'Alevtina',
                'gender' => '1'],
            ['name' => 'Александра', 'en_name'=>'Alexandadra',
                'gender' => '1'],
            ['name' => 'Алеста', 'en_name'=>'Alesta',
                'gender' => '1'],
            ['name' => 'Алина', 'en_name'=>'Alina',
                'gender' => '1'],
            ['name' => 'Алиса', 'en_name'=>'Alisa',
                'gender' => '1'],
            ['name' => 'Алия', 'en_name'=>'Aliya',
                'gender' => '1'],
            ['name' => 'Алла', 'en_name'=>'Alla',
                'gender' => '1'],
            ['name' => 'Алсу', 'en_name'=>'Alsu',
                'gender' => '1'],
            ['name' => 'Альба', 'en_name'=>'Alba',
                'gender' => '1'],
            ['name' => 'Альбина', 'en_name'=>'Albinda',
                'gender' => '1'],
            ['name' => 'Альфия', 'en_name'=>'Alphia',
                'gender' => '1'],
            ['name' => 'Аля', 'en_name'=>'Alya',
                'gender' => '1'],
            ['name' => 'Амалия', 'en_name'=>'Amalia',
                'gender' => '1'],
            ['name' => 'Амина', 'en_name'=>'Amina',
                'gender' => '1'],
            ['name' => 'Амира', 'en_name'=>'Amira',
                'gender' => '1'],
            ['name' => 'Анаит', 'en_name'=>'Anait',
                'gender' => '1'],
            ['name' => 'Анастасия', 'en_name'=>'Anastsia',
                'gender' => '1'],
            ['name' => 'Ангелина', 'en_name'=>'Angelina',
                'gender' => '1'],
            ['name' => 'Анжела', 'en_name'=>'Ahgela',
                'gender' => '1'],
            ['name' => 'Анжелика', 'en_name'=>'Angela',
                'gender' => '1'],
            ['name' => 'Анисья', 'en_name'=>'Anusia',
                'gender' => '1'],
            ['name' => 'Анна', 'en_name'=>'Anna',
                'gender' => '1'],
            ['name' => 'Антонина', 'en_name'=>'Antonia',
                'gender' => '1'],
            ['name' => 'Анфиса', 'en_name'=>'Anfisa',
                'gender' => '1'],
            ['name' => 'Аполлинария', 'en_name'=>'Apollinaria',
                'gender' => '1'],
            ['name' => 'Арабелла', 'en_name'=>'Arabella',
                'gender' => '1'],
            ['name' => 'Ариана', 'en_name'=>'Ariana',
                'gender' => '1'],
            ['name' => 'Арина', 'en_name'=>'Ariana',
                'gender' => '1'],
            ['name' => 'Асель', 'en_name'=>'Asel',
                'gender' => '1'],
            ['name' => 'Асия', 'en_name'=>'Asiya',
                'gender' => '1'],
            ['name' => 'Астрид', 'en_name'=>'Astrid',
                'gender' => '1'],
            ['name' => 'Ася', 'en_name'=>'Asya',
                'gender' => '1'],
            ['name' => 'Аэлита', 'en_name'=>'Aelita',
                'gender' => '1'],
            ['name' => 'Бажена', 'en_name'=>'Bagena',
                'gender' => '1'],
            ['name' => 'Беатрис', 'en_name'=>'Biatris',
                'gender' => '1'],
            ['name' => 'Бела', 'en_name'=>'Bella',
                'gender' => '1'],
            ['name' => 'Белинда', 'en_name'=>'Belinda',
                'gender' => '1'],
            ['name' => 'Берта', 'en_name'=>'Berta',
                'gender' => '1'],
            ['name' => 'Богдана', 'en_name'=>'Bogdana',
                'gender' => '1'],
            ['name' => 'Божена', 'en_name'=>'Bojena',
                'gender' => '1'],
            ['name' => 'Валентина', 'en_name'=>'Valinyna',
                'gender' => '1'],
            ['name' => 'Валерия', 'en_name'=>'Valeria',
                'gender' => '1'],
            ['name' => 'Ванда', 'en_name'=>'Vanda',
                'gender' => '1'],
            ['name' => 'Ванесса', 'en_name'=>'Vanessa',
                'gender' => '1'],
            ['name' => 'Варвара', 'en_name'=>'Varvara',
                'gender' => '1'],
            ['name' => 'Василина', 'en_name'=>'Vasislyna',
                'gender' => '1'],
            ['name' => 'Василиса', 'en_name'=>'Vasilisa',
                'gender' => '1'],
            ['name' => 'Венера', 'en_name'=>'Venera',
                'gender' => '1'],
            ['name' => 'Вера', 'en_name'=>'Vera',
                'gender' => '1'],
            ['name' => 'Вероника', 'en_name'=>'Veronika',
                'gender' => '1'],
            ['name' => 'Веста', 'en_name'=>'Vesta',
                'gender' => '1'],
            ['name' => 'Вета', 'en_name'=>'Veta',
                'gender' => '1'],
            ['name' => 'Викторина', 'en_name'=>'Victorina',
                'gender' => '1'],
            ['name' => 'Виктория', 'en_name'=>'Victoria',
                'gender' => '1'],
            ['name' => 'Вилена', 'en_name'=>'Vilena',
                'gender' => '1'],
            ['name' => 'Виола', 'en_name'=>'Viola',
                'gender' => '1'],
            ['name' => 'Виолетта', 'en_name'=>'Violeta',
                'gender' => '1'],
            ['name' => 'Вита', 'en_name'=>'Vita',
                'gender' => '1'],
            ['name' => 'Влада', 'en_name'=>'Vlada',
                'gender' => '1'],
            ['name' => 'Владана', 'en_name'=>'Vladana',
                'gender' => '1'],
            ['name' => 'Владислава', 'en_name'=>'Vladislava',
                'gender' => '1'],
            ['name' => 'Габриэлла', 'en_name'=>'Gabriella',
                'gender' => '1'],
            ['name' => 'Галина', 'en_name'=>'Galina',
                'gender' => '1'],
            ['name' => 'Галия', 'en_name'=>'Galiya',
                'gender' => '1'],
            ['name' => 'Генриетта', 'en_name'=>'Genrietta',
                'gender' => '1'],
            ['name' => 'Гоар', 'en_name'=>'Goar',
                'gender' => '1'],
            ['name' => 'Грета', 'en_name'=>'Gretta',
                'gender' => '1'],
            ['name' => 'Гульзира', 'en_name'=>'Gulzira',
                'gender' => '1'],
            ['name' => 'Гульмира', 'en_name'=>'Gulmira',
                'gender' => '1'],
            ['name' => 'Гульназ', 'en_name'=>'Gulnaz',
                'gender' => '1'],
            ['name' => 'Гульнара', 'en_name'=>'Gulnara',
                'gender' => '1'],
            ['name' => 'Гульшат', 'en_name'=>'Gulshat',
                'gender' => '1'],
            ['name' => 'Гюзель', 'en_name'=>'Guzel',
                'gender' => '1'],
            ['name' => 'Далида', 'en_name'=>'Dalida',
                'gender' => '1'],
            ['name' => 'Дамира', 'en_name'=>'Damira',
                'gender' => '1'],
            ['name' => 'Дана', 'en_name'=>'Dana',
                'gender' => '1'],
            ['name' => 'Даниэла', 'en_name'=>'Daniela',
                'gender' => '1'],
            ['name' => 'Дания', 'en_name'=>'Dania',
                'gender' => '1'],
            ['name' => 'Дара', 'en_name'=>'Dara',
                'gender' => '1'],
            ['name' => 'Дарина', 'en_name'=>'Darina',
                'gender' => '1'],
            ['name' => 'Дарья', 'en_name'=>'Daria',
                'gender' => '1'],
            ['name' => 'Даяна', 'en_name'=>'Dayana',
                'gender' => '1'],
            ['name' => 'Джамиля', 'en_name'=>'Jamiya',
                'gender' => '1'],
            ['name' => 'Дженна', 'en_name'=>'Jena',
                'gender' => '1'],
            ['name' => 'Дженнифер', 'en_name'=>'Jenifer',
                'gender' => '1'],
            ['name' => 'Джессика', 'en_name'=>'Jesica',
                'gender' => '1'],
            ['name' => 'Джиневра', 'en_name'=>'Jinevra',
                'gender' => '1'],
            ['name' => 'Диана', 'en_name'=>'Diana',
                'gender' => '1'],
            ['name' => 'Дильназ', 'en_name'=>'Dilnaz',
                'gender' => '1'],
            ['name' => 'Дильнара', 'en_name'=>'Dilnara',
                'gender' => '1'],
            ['name' => 'Диля', 'en_name'=>'Dilya',
                'gender' => '1'],
            ['name' => 'Дилярам', 'en_name'=>'Dilyaram',
                'gender' => '1'],
            ['name' => 'Дина', 'en_name'=>'Dina',
                'gender' => '1'],
            ['name' => 'Динара', 'en_name'=>'Dianara',
                'gender' => '1'],
            ['name' => 'Долорес', 'en_name'=>'Dolores',
                'gender' => '1'],
            ['name' => 'Доминика', 'en_name'=>'Domonika',
                'gender' => '1'],
            ['name' => 'Домна', 'en_name'=>'Domna',
                'gender' => '1'],
            ['name' => 'Домника', 'en_name'=>'Domnika',
                'gender' => '1'],
            ['name' => 'Ева', 'en_name'=>'Eva',
                'gender' => '1'],
            ['name' => 'Евангелина', 'en_name'=>'Evangelina',
                'gender' => '1'],
            ['name' => 'Евгения', 'en_name'=>'Evgenia',
                'gender' => '1'],
            ['name' => 'Евдокия', 'en_name'=>'Evdokia',
                'gender' => '1'],
            ['name' => 'Екатерина', 'en_name'=>'Ekaterina',
                'gender' => '1'],
            ['name' => 'Елена', 'en_name'=>'Elena',
                'gender' => '1'],
            ['name' => 'Елизавета', 'en_name'=>'Elizaveta',
                'gender' => '1'],
            ['name' => 'Есения', 'en_name'=>'Esenia',
                'gender' => '1'],
            ['name' => 'Жаклин', 'en_name'=>'Jaklin',
                'gender' => '1'],
            ['name' => 'Жанна', 'en_name'=>'Janna',
                'gender' => '1'],
            ['name' => 'Жансая', 'en_name'=>'Jansaya',
                'gender' => '1'],
            ['name' => 'Жасмин', 'en_name'=>'Jasmyn',
                'gender' => '1'],
            ['name' => 'Жозефина', 'en_name'=>'Josephine',
                'gender' => '1'],
            ['name' => 'Жоржина', 'en_name'=>'Jojina',
                'gender' => '1'],
            ['name' => 'Забава', 'en_name'=>'Zabava',
                'gender' => '1'],
            ['name' => 'Заира', 'en_name'=>'Zaira',
                'gender' => '1'],
            ['name' => 'Замира', 'en_name'=>'Zamira',
                'gender' => '1'],
            ['name' => 'Зара', 'en_name'=>'Zara',
                'gender' => '1'],
            ['name' => 'Зарема', 'en_name'=>'Zarema',
                'gender' => '1'],
            ['name' => 'Зарина', 'en_name'=>'Zarina',
                'gender' => '1'],
            ['name' => 'Земфира', 'en_name'=>'Zemfira',
                'gender' => '1'],
            ['name' => 'Зинаида', 'en_name'=>'Zinaida',
                'gender' => '1'],
            ['name' => 'Зита', 'en_name'=>'Zita',
                'gender' => '1'],
            ['name' => 'Злата', 'en_name'=>'Zlata',
                'gender' => '1'],
            ['name' => 'Златослава', 'en_name'=>'Zlatoslava',
                'gender' => '1'],
            ['name' => 'Зоряна', 'en_name'=>'Zoryana',
                'gender' => '1'],
            ['name' => 'Зоя', 'en_name'=>'Zoi',
                'gender' => '1'],
            ['name' => 'Зульфия', 'en_name'=>'Zulphia',
                'gender' => '1'],
            ['name' => 'Зухра', 'en_name'=>'Zuhra',
                'gender' => '1'],
            ['name' => 'Изабелла', 'en_name'=>'Isabella',
                'gender' => '1'],
            ['name' => 'Иллирика', 'en_name'=>'Illyryka',
                'gender' => '1'],
            ['name' => 'Илона', 'en_name'=>'Ilona',
                'gender' => '1'],
            ['name' => 'Ильзира', 'en_name'=>'Ilsira',
                'gender' => '1'],
            ['name' => 'Илюза', 'en_name'=>'Iluza',
                'gender' => '1'],
            ['name' => 'Инга', 'en_name'=>'Inga',
                'gender' => '1'],
            ['name' => 'Индира', 'en_name'=>'Indira',
                'gender' => '1'],
            ['name' => 'Инесса', 'en_name'=>'Inessa',
                'gender' => '1'],
            ['name' => 'Инна', 'en_name'=>'Inna',
                'gender' => '1'],
            ['name' => 'Иоанна', 'en_name'=>'Ioanna',
                'gender' => '1'],
            ['name' => 'Ира', 'en_name'=>'Ira',
                'gender' => '1'],
            ['name' => 'Ирада', 'en_name'=>'Irada',
                'gender' => '1'],
            ['name' => 'Ираида', 'en_name'=>'Iraida',
                'gender' => '1'],
            ['name' => 'Ирина', 'en_name'=>'Irina',
                'gender' => '1'],
            ['name' => 'Ирма', 'en_name'=>'Irma',
                'gender' => '1'],
            ['name' => 'Искра', 'en_name'=>'Iskra',
                'gender' => '1'],
            ['name' => 'Ия', 'en_name'=>'Iya',
                'gender' => '1'],
            ['name' => 'Камила', 'en_name'=>'Kamila',
                'gender' => '1'],
            ['name' => 'Камилла', 'en_name'=>'Kamilla',
                'gender' => '1'],
            ['name' => 'Кара', 'en_name'=>'Kara',
                'gender' => '1'],
            ['name' => 'Карина', 'en_name'=>'Karina',
                'gender' => '1'],
            ['name' => 'Каролина', 'en_name'=>'Karolina',
                'gender' => '1'],
            ['name' => 'Кира', 'en_name'=>'Kira',
                'gender' => '1'],
            ['name' => 'Клавдия', 'en_name'=>'Klavdia',
                'gender' => '1'],
            ['name' => 'Клара', 'en_name'=>'Klara',
                'gender' => '1'],
            ['name' => 'Кора', 'en_name'=>'Kora',
                'gender' => '1'],
            ['name' => 'Корнелия', 'en_name'=>'Kornelia',
                'gender' => '1'],
            ['name' => 'Кристина', 'en_name'=>'Kristine',
                'gender' => '1'],
            ['name' => 'Ксения', 'en_name'=>'Ksenia',
                'gender' => '1'],
            ['name' => 'Лада', 'en_name'=>'Lada',
                'gender' => '1'],
            ['name' => 'Лана', 'en_name'=>'Lana',
                'gender' => '1'],
            ['name' => 'Лара', 'en_name'=>'Lara',
                'gender' => '1'],
            ['name' => 'Лариса', 'en_name'=>'Larisa',
                'gender' => '1'],
            ['name' => 'Лаура', 'en_name'=>'Laura',
                'gender' => '1'],
            ['name' => 'Лейла', 'en_name'=>'Leyla',
                'gender' => '1'],
            ['name' => 'Леона', 'en_name'=>'Leona',
                'gender' => '1'],
            ['name' => 'Лера', 'en_name'=>'Lera',
                'gender' => '1'],
            ['name' => 'Леся', 'en_name'=>'Lesya',
                'gender' => '1'],
            ['name' => 'Лиана', 'en_name'=>'Liana',
                'gender' => '1'],
            ['name' => 'Лидия', 'en_name'=>'Lidia',
                'gender' => '1'],
            ['name' => 'Лика', 'en_name'=>'Lika',
                'gender' => '1'],
            ['name' => 'Лили', 'en_name'=>'Lily',
                'gender' => '1'],
            ['name' => 'Лилиана', 'en_name'=>'Liliana',
                'gender' => '1'],
            ['name' => 'Лилия', 'en_name'=>'Lily',
                'gender' => '1'],
            ['name' => 'Лина', 'en_name'=>'Lina',
                'gender' => '1'],
            ['name' => 'Линда', 'en_name'=>'Linda',
                'gender' => '1'],
            ['name' => 'Лиора', 'en_name'=>'Liora',
                'gender' => '1'],
            ['name' => 'Лира', 'en_name'=>'Lira',
                'gender' => '1'],
            ['name' => 'Лия', 'en_name'=>'Lia',
                'gender' => '1'],
            ['name' => 'Лола', 'en_name'=>'Lola',
                'gender' => '1'],
            ['name' => 'Лолита', 'en_name'=>'Lolita',
                'gender' => '1'],
            ['name' => 'Лора', 'en_name'=>'Lora',
                'gender' => '1'],
            ['name' => 'Луиза', 'en_name'=>'Luisa',
                'gender' => '1'],
            ['name' => 'Лукерья', 'en_name'=>'Lukeria',
                'gender' => '1'],
            ['name' => 'Лукия', 'en_name'=>'Lukia',
                'gender' => '1'],
            ['name' => 'Любава', 'en_name'=>'Lubava',
                'gender' => '1'],
            ['name' => 'Любовь', 'en_name'=>'Lubov',
                'gender' => '1'],
            ['name' => 'Людмила', 'en_name'=>'Ludmilla',
                'gender' => '1'],
            ['name' => 'Люсиль', 'en_name'=>'Lusil',
                'gender' => '1'],
            ['name' => 'Люсьена', 'en_name'=>'Lusien',
                'gender' => '1'],
            ['name' => 'Люция', 'en_name'=>'Lucie',
                'gender' => '1'],
            ['name' => 'Люче', 'en_name'=>'Luche',
                'gender' => '1'],
            ['name' => 'Ляйсан', 'en_name'=>'Lyasun',
                'gender' => '1'],
            ['name' => 'Ляля', 'en_name'=>'Lyalya',
                'gender' => '1'],
            ['name' => 'Мавиле', 'en_name'=>'Mavile',
                'gender' => '1'],
            ['name' => 'Мавлюда', 'en_name'=>'Mavlyuda',
                'gender' => '1'],
            ['name' => 'Магда', 'en_name'=>'Magda',
                'gender' => '1'],
            ['name' => 'Магдалeна', 'en_name'=>'Magdalena',
                'gender' => '1'],
            ['name' => 'Мадина', 'en_name'=>'Madina',
                'gender' => '1'],
            ['name' => 'Мадлен', 'en_name'=>'Madlen',
                'gender' => '1'],
            ['name' => 'Майя', 'en_name'=>'Majya',
                'gender' => '1'],
            ['name' => 'Макария', 'en_name'=>'Makariya',
                'gender' => '1'],
            ['name' => 'Малика', 'en_name'=>'Malika',
                'gender' => '1'],
            ['name' => 'Мара', 'en_name'=>'Mara',
                'gender' => '1'],
            ['name' => 'Маргарита', 'en_name'=>'Margarita',
                'gender' => '1'],
            ['name' => 'Марианна', 'en_name'=>'Marianna',
                'gender' => '1'],
            ['name' => 'Марика', 'en_name'=>'Marika',
                'gender' => '1'],
            ['name' => 'Марина', 'en_name'=>'Marina',
                'gender' => '1'],
            ['name' => 'Мария', 'en_name'=>'Mariya',
                'gender' => '1'],
            ['name' => 'Мариям', 'en_name'=>'Mariyam',
                'gender' => '1'],
            ['name' => 'Марта', 'en_name'=>'Marta',
                'gender' => '1'],
            ['name' => 'Марфа', 'en_name'=>'Marfa',
                'gender' => '1'],
            ['name' => 'Мелания', 'en_name'=>'Melaniya',
                'gender' => '1'],
            ['name' => 'Мелисса', 'en_name'=>'Melissa',
                'gender' => '1'],
            ['name' => 'Мика', 'en_name'=>'Mika',
                'gender' => '1'],
            ['name' => 'Мила', 'en_name'=>'Mila',
                'gender' => '1'],
            ['name' => 'Милада', 'en_name'=>'Milada',
                'gender' => '1'],
            ['name' => 'Милана', 'en_name'=>'Milana',
                'gender' => '1'],
            ['name' => 'Милен', 'en_name'=>'Milen',
                'gender' => '1'],
            ['name' => 'Милена', 'en_name'=>'Milena',
                'gender' => '1'],
            ['name' => 'Милица', 'en_name'=>'Milica',
                'gender' => '1'],
        ]);
    }

}
