<?php

use Illuminate\Database\Seeder;

class ThUserNamesSeeder extends Seeder {

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
        // DB::table('user_names')->truncate();

        \App\Models\UserNames::insert([

            ['name' => 'Мира', 'en_name' => 'Mira',
                'gender' => '1'],
            ['name' => 'Мирослава', 'en_name' => 'Miroslava',
                'gender' => '1'],
            ['name' => 'Мирра', 'en_name' => 'Mirra',
                'gender' => '1'],
            ['name' => 'Мия', 'en_name' => 'Miya',
                'gender' => '1'],
            ['name' => 'Моника', 'en_name' => 'Monika',
                'gender' => '1'],
            ['name' => 'Муза', 'en_name' => 'Muza',
                'gender' => '1'],
            ['name' => 'Надежда', 'en_name' => 'Nadezhda',
                'gender' => '1'],
            ['name' => 'Наиля', 'en_name' => 'Nailya',
                'gender' => '1'],
            ['name' => 'Наима', 'en_name' => 'Naima',
                'gender' => '1'],
            ['name' => 'Нана', 'en_name' => 'Nana',
                'gender' => '1'],
            ['name' => 'Наоми', 'en_name' => 'Naomi',
                'gender' => '1'],
            ['name' => 'Наргиза', 'en_name' => 'Nargiza',
                'gender' => '1'],
            ['name' => 'Наталья', 'en_name' => 'Natalya',
                'gender' => '1'],
            ['name' => 'Нелли', 'en_name' => 'Nelli',
                'gender' => '1'],
            ['name' => 'Нея', 'en_name' => 'Neya',
                'gender' => '1'],
            ['name' => 'Ника', 'en_name' => 'Nika',
                'gender' => '1'],
            ['name' => 'Николь', 'en_name' => 'Nikol',
                'gender' => '1'],
            ['name' => 'Нина', 'en_name' => 'Nina',
                'gender' => '1'],
            ['name' => 'Нинель', 'en_name' => 'Ninel',
                'gender' => '1'],
            ['name' => 'Номина', 'en_name' => 'Nomina',
                'gender' => '1'],
            ['name' => 'Нора', 'en_name' => 'Nora',
                'gender' => '1'],
            ['name' => 'Нурия', 'en_name' => 'Nuriya',
                'gender' => '1'],
            ['name' => 'Одетта', 'en_name' => 'Odetta',
                'gender' => '1'],
            ['name' => 'Оксана', 'en_name' => 'Oksana',
                'gender' => '1'],
            ['name' => 'Октябрина', 'en_name' => 'Oktyabrina',
                'gender' => '1'],
            ['name' => 'Олеся', 'en_name' => 'Olesya',
                'gender' => '1'],
            ['name' => 'Оливия', 'en_name' => 'Oliviya',
                'gender' => '1'],
            ['name' => 'Ольга', 'en_name' => 'Olga',
                'gender' => '1'],
            ['name' => 'Офелия', 'en_name' => 'Ofeliya',
                'gender' => '1'],
            ['name' => 'Павлина', 'en_name' => 'Pavlina',
                'gender' => '1'],
            ['name' => 'Патриция', 'en_name' => 'Patriciya',
                'gender' => '1'],
            ['name' => 'Паула', 'en_name' => 'Paula',
                'gender' => '1'],
            ['name' => 'Пейтон', 'en_name' => 'Pejton',
                'gender' => '1'],
            ['name' => 'Пелагея', 'en_name' => 'Pelageya',
                'gender' => '1'],
            ['name' => 'Перизат', 'en_name' => 'Perizat',
                'gender' => '1'],
            ['name' => 'Платонида', 'en_name' => 'Platonida',
                'gender' => '1'],
            ['name' => 'Полина', 'en_name' => 'Polina',
                'gender' => '1'],
            ['name' => 'Прасковья', 'en_name' => 'Praskovya',
                'gender' => '1'],
            ['name' => 'Сабина', 'en_name' => 'Sabina',
                'gender' => '1'],
            ['name' => 'Сабрина', 'en_name' => 'Sabrina',
                'gender' => '1'],
            ['name' => 'Сажида', 'en_name' => 'Sazhida',
                'gender' => '1'],
            ['name' => 'Саида', 'en_name' => 'Saida',
                'gender' => '1'],
            ['name' => 'Самира', 'en_name' => 'Samira',
                'gender' => '1'],
            ['name' => 'Сандра', 'en_name' => 'Sandra',
                'gender' => '1'],
            ['name' => 'Сания', 'en_name' => 'Saniya',
                'gender' => '1'],
            ['name' => 'Сара', 'en_name' => 'Sara',
                'gender' => '1'],
            ['name' => 'Сати', 'en_name' => 'Sati',
                'gender' => '1'],
            ['name' => 'Сафия', 'en_name' => 'Safiya',
                'gender' => '1'],
            ['name' => 'Сафура', 'en_name' => 'Safura',
                'gender' => '1'],
            ['name' => 'Светлана', 'en_name' => 'Svetlana',
                'gender' => '1'],
            ['name' => 'Севара', 'en_name' => 'Sevara',
                'gender' => '1'],
            ['name' => 'Серафима', 'en_name' => 'Serafima',
                'gender' => '1'],
            ['name' => 'Сильвия', 'en_name' => 'Silviya',
                'gender' => '1'],
            ['name' => 'Снежана', 'en_name' => 'Snezhana',
                'gender' => '1'],
            ['name' => 'Соня', 'en_name' => 'Sonya',
                'gender' => '1'],
            ['name' => 'Софья', 'en_name' => 'Sofya',
                'gender' => '1'],
            ['name' => 'Стелла', 'en_name' => 'Stella',
                'gender' => '1'],
            ['name' => 'Стефания', 'en_name' => 'Stefaniya',
                'gender' => '1'],
            ['name' => 'Сусанна', 'en_name' => 'Susanna',
                'gender' => '1'],
            ['name' => 'Таисия', 'en_name' => 'Taisiya',
                'gender' => '1'],
            ['name' => 'Тамара', 'en_name' => 'Tamara',
                'gender' => '1'],
            ['name' => 'Тамила', 'en_name' => 'Tamila',
                'gender' => '1'],
            ['name' => 'Тара', 'en_name' => 'Tara',
                'gender' => '1'],
            ['name' => 'Татьяна', 'en_name' => 'Tatyana',
                'gender' => '1'],
            ['name' => 'Таяна', 'en_name' => 'Tayana',
                'gender' => '1'],
            ['name' => 'Теона', 'en_name' => 'Teona',
                'gender' => '1'],
            ['name' => 'Тереза', 'en_name' => 'Tereza',
                'gender' => '1'],
            ['name' => 'Тина', 'en_name' => 'Tina',
                'gender' => '1'],
            ['name' => 'Томирис', 'en_name' => 'Tomiris',
                'gender' => '1'],
            ['name' => 'Тора', 'en_name' => 'Tora',
                'gender' => '1'],
            ['name' => 'Ульяна', 'en_name' => 'Ulyana',
                'gender' => '1'],
            ['name' => 'Урсула', 'en_name' => 'Ursula',
                'gender' => '1'],
            ['name' => 'Устинья', 'en_name' => 'Ustinya',
                'gender' => '1'],
            ['name' => 'Фёкла', 'en_name' => 'Fyokla',
                'gender' => '1'],
            ['name' => 'Фазиля', 'en_name' => 'Fazilya',
                'gender' => '1'],
            ['name' => 'Фаина', 'en_name' => 'Faina',
                'gender' => '1'],
            ['name' => 'Фарида', 'en_name' => 'Farida',
                'gender' => '1'],
            ['name' => 'Фариза', 'en_name' => 'Fariza',
                'gender' => '1'],
            ['name' => 'Фатима', 'en_name' => 'Fatima',
                'gender' => '1'],
            ['name' => 'Феруза', 'en_name' => 'Feruza',
                'gender' => '1'],
            ['name' => 'Фируза', 'en_name' => 'Firuza',
                'gender' => '1'],
            ['name' => 'Флора', 'en_name' => 'Flora',
                'gender' => '1'],
            ['name' => 'Флорентина', 'en_name' => 'Florentina',
                'gender' => '1'],
            ['name' => 'Флориана', 'en_name' => 'Floriana',
                'gender' => '1'],
            ['name' => 'Фредерика', 'en_name' => 'Frederika',
                'gender' => '1'],
            ['name' => 'Фрида', 'en_name' => 'Frida',
                'gender' => '1'],
            ['name' => 'Хадия', 'en_name' => 'Xadiya',
                'gender' => '1'],
            ['name' => 'Хилари', 'en_name' => 'Xilari',
                'gender' => '1'],
            ['name' => 'Хлоя', 'en_name' => 'Xloya',
                'gender' => '1'],
            ['name' => 'Цагана', 'en_name' => 'Cagana',
                'gender' => '1'],
            ['name' => 'Цветана', 'en_name' => 'Cvetana',
                'gender' => '1'],
            ['name' => 'Челси', 'en_name' => 'Chelsi',
                'gender' => '1'],
            ['name' => 'Чеслава', 'en_name' => 'Cheslava',
                'gender' => '1'],
            ['name' => 'Чулпан', 'en_name' => 'Chulpan',
                'gender' => '1'],
            ['name' => 'Шакира', 'en_name' => 'Shakira',
                'gender' => '1'],
            ['name' => 'Шарлотта', 'en_name' => 'Sharlotta',
                'gender' => '1'],
            ['name' => 'Шахина', 'en_name' => 'Shaxina',
                'gender' => '1'],
            ['name' => 'Шейла', 'en_name' => 'Shejla',
                'gender' => '1'],
            ['name' => 'Шелли', 'en_name' => 'Shelli',
                'gender' => '1'],
            ['name' => 'Шерил', 'en_name' => 'Sheril',
                'gender' => '1'],
            ['name' => 'Эвелина', 'en_name' => 'Evelina',
                'gender' => '1'],
            ['name' => 'Эвита', 'en_name' => 'Evita',
                'gender' => '1'],
            ['name' => 'Элеонора', 'en_name' => 'Eleonora',
                'gender' => '1'],
            ['name' => 'Элиана', 'en_name' => 'Eliana',
                'gender' => '1'],
            ['name' => 'Элиза', 'en_name' => 'Eliza',
                'gender' => '1'],
            ['name' => 'Элина', 'en_name' => 'Elina',
                'gender' => '1'],
            ['name' => 'Элла', 'en_name' => 'Ella',
                'gender' => '1'],
            ['name' => 'Эльвина', 'en_name' => 'Elvina',
                'gender' => '1'],
            ['name' => 'Эльвира', 'en_name' => 'Elvira',
                'gender' => '1'],
            ['name' => 'Эльмира', 'en_name' => 'Elmira',
                'gender' => '1'],
            ['name' => 'Эльнара', 'en_name' => 'Elnara',
                'gender' => '1'],
            ['name' => 'Эля', 'en_name' => 'Elya',
                'gender' => '1'],
            ['name' => 'Эмили', 'en_name' => 'Emili',
                'gender' => '1'],
            ['name' => 'Эмилия', 'en_name' => 'Emiliya',
                'gender' => '1'],
            ['name' => 'Эмма', 'en_name' => 'Emma',
                'gender' => '1'],
            ['name' => 'Энже', 'en_name' => 'Enzhe',
                'gender' => '1'],
            ['name' => 'Эрика', 'en_name' => 'Erika',
                'gender' => '1'],
            ['name' => 'Эрмина', 'en_name' => 'Ermina',
                'gender' => '1'],
            ['name' => 'Эсмеральда', 'en_name' => 'Esmeralda',
                'gender' => '1'],
            ['name' => 'Эсмира', 'en_name' => 'Esmira',
                'gender' => '1'],
            ['name' => 'Этель', 'en_name' => 'Etel',
                'gender' => '1'],
            ['name' => 'Этери', 'en_name' => 'Eteri',
                'gender' => '1'],
            ['name' => 'Юлия', 'en_name' => 'Yuliya',
                'gender' => '1'],
            ['name' => 'Юна', 'en_name' => 'Yuna',
                'gender' => '1'],
            ['name' => 'Юния', 'en_name' => 'Yuniya',
                'gender' => '1'],
            ['name' => 'Юнона', 'en_name' => 'Yunona',
                'gender' => '1'],
            ['name' => 'Ядвига', 'en_name' => 'Yadviga',
                'gender' => '1'],
            ['name' => 'Яна', 'en_name' => 'Yana',
                'gender' => '1'],
            ['name' => 'Янина', 'en_name' => 'Yanina',
                'gender' => '1'],
            ['name' => 'Ярина', 'en_name' => 'Yarina',
                'gender' => '1'],
            ['name' => 'Ярослава', 'en_name' => 'Yaroslava',
                'gender' => '1'],
            ['name' => 'Ясмина', 'en_name' => 'Yasmina',
                'gender' => '1'],
        ]);
    }

}
