<?php

use Illuminate\Database\Seeder;

class UserNamesTableSeeder extends Seeder {

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
        DB::table('user_names')->truncate();

        \App\Models\UserNames::insert([
            ['name' => 'Абрам', 'en_name'=>'Abram'],
            ['name' => 'Аваз', 'en_name'=>'Avaz'],
            ['name' => 'Августин', 'en_name'=>'Augustin'],
            ['name' => 'Авраам', 'en_name'=>'Avraam'],
            ['name' => 'Агап', 'en_name'=>'Agap'],
            ['name' => 'Агапит', 'en_name'=>'Agapyt'],
            ['name' => 'Агафон', 'en_name'=>'Agaphon'],
            ['name' => 'Адам', 'en_name'=>'Adam'],
            ['name' => 'Адриан', 'en_name'=>'Adrian'],
            ['name' => 'Азамат', 'en_name'=>'Azamat'],
            ['name' => 'Азат', 'en_name'=>'Azat'],
            ['name' => 'Айдар', 'en_name'=>'Aidar'],
            ['name' => 'Айрат', 'en_name'=>'Airat'],
            ['name' => 'Акакий', 'en_name'=>'Akakiy'],
            ['name' => 'Аким', 'en_name'=>'Akim'],
            ['name' => 'Алан', 'en_name'=>'Alan'],
            ['name' => 'Александр', 'en_name'=>'Aleksandr'],
            ['name' => 'Алексей', 'en_name'=>'Aleksey'],
            ['name' => 'Али', 'en_name'=>'Ali'],
            ['name' => 'Алик', 'en_name'=>'Alik'],
            ['name' => 'Алихан', 'en_name'=>'Alihan'],
            ['name' => 'Алмаз', 'en_name'=>'Almaz'],
            ['name' => 'Альберт', 'en_name'=>'Albert'],
            ['name' => 'Амир', 'en_name'=>'Amir'],
            ['name' => 'Амирам', 'en_name'=>'Amiram'],
            ['name' => 'Анар', 'en_name'=>'Anar'],
            ['name' => 'Анастасий', 'en_name'=>'Anastiy'],
            ['name' => 'Анатолий', 'en_name'=>'Anatoliy'],
            ['name' => 'Ангел', 'en_name'=>'Angel'],
            ['name' => 'Андрей', 'en_name'=>'Andrey'],
            ['name' => 'Антон', 'en_name'=>'Anton'],
            ['name' => 'Анфим', 'en_name'=>'Anfim'],
            ['name' => 'Арам', 'en_name'=>'Aram'],
            ['name' => 'Аристарх', 'en_name'=>'Arisatarh'],
            ['name' => 'Аркадий', 'en_name'=>'Arkadiy'],
            ['name' => 'Арман', 'en_name'=>'Armun'],
            ['name' => 'Армен', 'en_name'=>'Arman'],
            ['name' => 'Арсен', 'en_name'=>'Arsen'],
            ['name' => 'Арсений', 'en_name'=>'Arseniy'],
            ['name' => 'Арслан', 'en_name'=>'Arsan'],
            ['name' => 'Артём', 'en_name'=>'Artem'],
            ['name' => 'Артемий', 'en_name'=>'Artemiy'],
            ['name' => 'Артур', 'en_name'=>'Artyr'],
            ['name' => 'Асхан', 'en_name'=>'Ashan'],
            ['name' => 'Ахмет', 'en_name'=>'Ahmet'],
            ['name' => 'Ашот', 'en_name'=>'Ashot'],
            ['name' => 'Бахрам', 'en_name'=>'Bahram'],
            ['name' => 'Блез', 'en_name'=>'Brez'],
            ['name' => 'Богдан', 'en_name'=>'Bogdan'],
            ['name' => 'Борис', 'en_name'=>'Boris'],
            ['name' => 'Борислав', 'en_name'=>'Borislav'],
            ['name' => 'Бронислав', 'en_name'=>'Bronislav'],
            ['name' => 'Булат', 'en_name'=>'Bulat'],
            ['name' => 'Вадим', 'en_name'=>'Vadym'],
            ['name' => 'Валентин', 'en_name'=>'Valentyn'],
            ['name' => 'Валерий', 'en_name'=>'Valeriy'],
            ['name' => 'Вальдемар', 'en_name'=>'Valdemar'],
            ['name' => 'Вардан', 'en_name'=>'Vardan'],
            ['name' => 'Василий', 'en_name'=>'Vasiliy'],
            ['name' => 'Вениамин', 'en_name'=>'Veniamyn'],
            ['name' => 'Виктор', 'en_name'=>'Victor'],
            ['name' => 'Вильгельм', 'en_name'=>'Vilgelm'],
            ['name' => 'Вит', 'en_name'=>'Vyt'],
            ['name' => 'Виталий', 'en_name'=>'Vitaliy'],
            ['name' => 'Владимир', 'en_name'=>'Vladymyr'],
            ['name' => 'Владислав', 'en_name'=>'Vladyslav'],
            ['name' => 'Владлен', 'en_name'=>'Vladlen'],
            ['name' => 'Влас', 'en_name'=>'Vlas'],
            ['name' => 'Всеволод', 'en_name'=>'Vsevolod'],
            ['name' => 'Вячеслав', 'en_name'=>'Vyacheslav'],
            ['name' => 'Гавриил', 'en_name'=>'Gavriyl'],
            ['name' => 'Гамлет', 'en_name'=>'Hamlet'],
            ['name' => 'Гарри', 'en_name'=>'Garry'],
            ['name' => 'Геннадий', 'en_name'=>'Gennadiy'],
            ['name' => 'Генри', 'en_name'=>'Genry'],
            ['name' => 'Генрих', 'en_name'=>'Genrih'],
            ['name' => 'Георгий', 'en_name'=>'George'],
            ['name' => 'Герасим', 'en_name'=>'Gerasim'],
            ['name' => 'Герман', 'en_name'=>'Herman'],
            ['name' => 'Германн', 'en_name'=>'Hermann'],
            ['name' => 'Глеб', 'en_name'=>'Gleb'],
            ['name' => 'Гордей', 'en_name'=>'Gordey'],
            ['name' => 'Григорий', 'en_name'=>'Grigoriy'],
            ['name' => 'Густав', 'en_name'=>'Gustav'],
            ['name' => 'Давид', 'en_name'=>'David'],
            ['name' => 'Давлат', 'en_name'=>'Davlat'],
            ['name' => 'Дамир', 'en_name'=>'Damyr'],
            ['name' => 'Дана', 'en_name'=>'Dana'],
            ['name' => 'Даниил', 'en_name'=>'Daniyl'],
            ['name' => 'Данислав', 'en_name'=>'Danyslav'],
            ['name' => 'Данияр', 'en_name'=>'Daniyar'],
            ['name' => 'Дарий', 'en_name'=>'Dariy'],
            ['name' => 'Даурен', 'en_name'=>'Dauren'],
            ['name' => 'Демид', 'en_name'=>'Demid'],
            ['name' => 'Демьян', 'en_name'=>'Demian'],
            ['name' => 'Денис', 'en_name'=>'Denis'],
            ['name' => 'Джамал', 'en_name'=>'Jamal'],
            ['name' => 'Джеймс', 'en_name'=>'James'],
            ['name' => 'Джозеф', 'en_name'=>'Jothef'],
            ['name' => 'Джонатан', 'en_name'=>'Jonatan'],
            ['name' => 'Дик', 'en_name'=>'Dik'],
            ['name' => 'Динар', 'en_name'=>'Dinar'],
            ['name' => 'Дино', 'en_name'=>'Dino'],
            ['name' => 'Дмитрий', 'en_name'=>'Dmitry'],
            ['name' => 'Добрыня', 'en_name'=>'Dobrinya'],
            ['name' => 'Доминик', 'en_name'=>'Dominik'],
            ['name' => 'Евгений', 'en_name'=>'Evgeniy'],
            ['name' => 'Евдоким', 'en_name'=>'Evdokiy'],
            ['name' => 'Евсей', 'en_name'=>'Evsey'],
            
        ]);
    }

}
